apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kviklet
spec:
  releaseName: kviklet
  chart:
    spec:
      chart: ./kviklet
      sourceRef:
        kind: GitRepository
        name: 
        namespace: 
  interval: 5m0s
  values:
    image: ghcr.io/kviklet/kviklet:0.4.0
    dataSourceUrl: jdbc:postgresql://localhost:5432/v1_kviklet
    port: 80
    oidc:
      enabled: true
      provider: "gitlab"
      issuer: "https://gitlab.com"
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
  valuesFrom:
    - kind: Secret
      name: kviklet-secret
      valuesKey: values.yaml
  rollback:
    disableWait: true
    cleanupOnFail: true
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  maxHistory: 3