# This a example plain secret please encrypt it self 
apiVersion: v1
stringData:
    values.yaml: |
        config:
          datasource:
            username: appkviklet
            password: databasepassword
          initialUser:
            email: admin@example.com
            password: someverysecurepassword
          oidc:
            clientId: abcd1234
            clientSecret: abcd1234
kind: Secret
metadata:
    name: kviklet-secret
type: Opaque
