apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}-config-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kviklet.metaLabels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://kviklet-demo-postgresql:5432/kviklet"
  INITIAL_USER_EMAIL: "jascha@kviklet.dev"
  INITIAL_USER_PASSWORD: "jascha"