{{- if not .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kviklet.metaLabels" . | nindent 4 }}
type: Opaque
data:
  datasource-username: {{ .Values.config.datasource.username | b64enc | quote }}
  postgres-password: {{ .Values.config.datasource.password | b64enc | quote }}
{{- end }}
