apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  datasource-username: {{ .Values.config.datasource.username }}
  datasource-password: {{ .Values.config.datasource.password }}
  initialUser-email: {{ .Values.config.initialUser.email }}
  initialUser-password: {{ .Values.config.initialUser.password }}
  oidc-clientId: {{ .Values.config.oidc.clientId }}
  oidc-clientSecret: {{ .Values.config.oidc.clientSecret }}

