apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}-config-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "fullname" . }}
    release: "{{ .Release.Name }}"
type: Opaque
data:
  initialUser-email: {{ .Values.config.initialUser.email | b64enc | quote }}
  initialUser-password: {{ default (randAlphaNum 20) .Values.config.initialUser.password | b64enc | quote }}
  {{- if .Values.config.oidc.enabled }}
  oidc-clientId: {{ .Values.config.oidc.clientId | b64enc | quote }}
  oidc-clientSecret: {{ .Values.config.oidc.clientSecret | b64enc | quote }}
  {{- end }}

