---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: {{ include "fullname" . }}
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: 8080
  selector:
      app: {{ include "fullname" . }}
      release: "{{ .Release.Name }}"
