version: "3"
services:
  freeipa:
    image: freeipa/freeipa-server:almalinux-9
    platform: linux/arm64
    container_name: freeipa-server
    hostname: ipa.example.test
    environment:
      - IPA_SERVER_HOSTNAME=ipa.example.test
      - IPA_SERVER_IP=172.20.0.2
      - DEBUG_TRACE=1
      - DEBUG_NO_EXIT=1
      - PASSWORD=Secret123
    command:
      - ipa-server-install
      - -U
      - --domain=example.test
      - --realm=EXAMPLE.TEST
      - --ds-password=directory_password
      - --admin-password=admin_password
      - --no-ntp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ipa-data:/data:Z
    networks:
      ipa_network:
        ipv4_address: 172.20.0.2
    privileged: true
    dns:
      - 172.20.0.2
    dns_search:
      - example.test
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

networks:
  ipa_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  ipa-data:
